### ISSUE TITLE
Panic when return value is a struct

### ISSUE THREAD

**Issue by arp242** [stapelberg/expanderr#7]
When I set the return value to `(sting, error)` the tool neatly sets the return value to `return "", err`; cool! But with a struct I get a panic:

```
[~/go/src/a/err]% cat err.go
package err

import "os"

type X struct{}

func err() (X, error) {
        os.Remove("/tmp/state.bin")
        return X{}, nil
}

[~/go/src/a/err]% expanderr err.go:#75 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x555d0a]

goroutine 1 [running]:
go/printer.(*printer).indentList(0xc42082b6d0, 0xc420c8eb00, 0x2, 0x2, 0xc420c740b0)
	/usr/lib/go/src/go/printer/nodes.go:1062 +0x4a
go/printer.(*printer).stmt(0xc42082b6d0, 0x81bda0, 0xc420c8eba0, 0x101)
	/usr/lib/go/src/go/printer/nodes.go:1159 +0x1cf4
go/printer.(*printer).stmtList(0xc42082b6d0, 0xc4202aedc0, 0x1, 0x1, 0x1, 0x81f701)
	/usr/lib/go/src/go/printer/nodes.go:948 +0x109
go/printer.(*printer).block(0xc42082b6d0, 0xc4207a4150, 0x1)
	/usr/lib/go/src/go/printer/nodes.go:971 +0x103
go/printer.(*printer).stmt(0xc42082b6d0, 0x81bb20, 0xc420a16540, 0x81bb00)
	/usr/lib/go/src/go/printer/nodes.go:1181 +0x256d
go/printer.(*printer).printNode(0xc42082b6d0, 0x68ff00, 0xc420a16540, 0xc420ce3fc0, 0x0)
	/usr/lib/go/src/go/printer/printer.go:1130 +0x414
go/printer.(*Config).fprint(0x8177d0, 0x818460, 0xc4200a2e70, 0xc4200a4340, 0x68ff00, 0xc420a16540, 0xc4207a41b0, 0x68, 0x6aaa00)
	/usr/lib/go/src/go/printer/printer.go:1288 +0x178
go/printer.(*Config).Fprint(0x8177d0, 0x818460, 0xc4200a2e70, 0xc4200a4340, 0x68ff00, 0xc420a16540, 0xc42002e380, 0x7fa543e18d90)
	/usr/lib/go/src/go/printer/printer.go:1346 +0x99
go/format.Node(0x818460, 0xc4200a2e70, 0xc4200a4340, 0x68ff00, 0xc420a16540, 0x0, 0x0)
	/usr/lib/go/src/go/format/format.go:70 +0xd8
main.logic(0x818aa0, 0xc420090008, 0x837c40, 0x7ffc696167cc, 0xa, 0x0, 0x0)
	/home/martin/go/src/github.com/stapelberg/expanderr/expanderr.go:572 +0xa7f
main.main()
	/home/martin/go/src/github.com/stapelberg/expanderr/expanderr.go:669 +0xbd

```

**Comment by arp242** [comment]
Actually it's not just structs, `type foo string` also panics. It's on all custom types.
